
attrColNames = [
  // y
  {class:"y", name:"Avg Cycle Years",column:"batcyc_a_v",format:",.1f"   },
  {class:"y", name:"Tot Cycle Years",column:"batcyc_n_v",format:",.1f"  },
  {class:"y", name:"Repeat Jobs #",column:"batcyc_jobs_n_v",format:",.1f"  },
  {class:"y", name:"Repeat Jobs %",column:"batcyc_n_r",format:".2%"  },
  {class:'y',name:"Prospect #", column:'prospect_n_v',format:"0.3s" },
  {class:'y',name:"Repeat #"  , column:'purchase_n_v',format:"0.3s" },
  {class:'y',name:"Repeat %"  , column:'purchase_r_v',format:".2%"},
  {class:'y',name:"Sales #"  , column:'jobs_n_v',format:",.0f"},
  {class:'y',name:"Avg Sale $",column:'price_a_v',format:"$0.3s"},
  {class:'y',name:"Sold #",column:'sold_n_v',format:"0.3s"},
  {class:'y',name:"Sum Sale $",column:'price_n_v',format:"$0.3s"},
  {class:'y',name:"Sum Lifecycle"  , column:'battlife_n_v',format:"0.3s"},
  {class:'y',name:"Avg Lifecycle"  , column:'battlife_r_v',format:"0.1f"},
  {class:'y',name:"Sum Batt Price"  , column:'nrma_price_n_v',format:"0.3s"},
  {class:'y',name:"Avg Batt Price"  , column:'nrma_price_r_v',format:"0.3s"},
  {class:'y',name:"Repeat # Prediction"  , column:'purchase_pred_n_v',format:"0.3s"},
  {class:'y',name:"Repeat % Prediction"  , column:'purchase_pred_r_v',format:".2%"},
  {class:'y',name:"Repeat #"  , column:'bat_repeat_n_v',format:"0.3s"},
  {class:'y',name:"Repeat %"  , column:'bat_repeat_n_r',format:".2%"},
  {class:'y',name:"Callouts"  , column:'callout_n_v',format:".3s"},
  // nba
  {class:'y',name:"Repeat %"  , column:'first_insurance_r_v',format:".2%"},

  
  // renewals
  {class:'y',name:"Churn %"  , column:'churn_r_v',format:".2%"},
  {class:'y',name:"Churn CVM %"  , column:'churn_180lag_r_v',format:".2%"},

  {class:'y',name:"Churn #"  , column:'churn_n_v',format:".3s"},
  {class:'y',name:"Churn CVM #" , column:'churn_180lag_n_v',format:".3s"},
  
  {class:'y',name:"Renew #"  , column:'renewed_n_v',format:".3s"},
  {class:'y',name:"Renewed CVM #" , column:'renewed_180lag_n_v',format:".3s"},
  {class:'y',name:"Renewals #"  , column:'renewal_n_v',format:".3s"},
  {class:'y',name:"Renew %"  , column:'renewed_r_v',format:".2%"},
  {class:'y',name:"Renewed CVM %" , column:'renewed_180lag_r_v',format:".2%"},

  // titanic

  {class:'y',name:"Train Survived %"  , column:'survived_r_v',format:".0%"},
  {class:'y',name:"Train Passengers #"  , column:'passengers_n_v',format:".3s"},
  {class:'y',name:"train Survived #"  , column:'survived_n_v',format:".3s"},
  {class:'y',name:"All Passengers #"  , column:'total_n_v',format:".3s"},


  // x
  {class:'x',name:'Location SA4', column:'loc_sa4'},
  {class:'x',name:'Addon: Key', column:'addon_key'},
  {class:'x',name:'Addon: Pet', column:'addon_pet'},
  {class:'x',name:'Addon: Tow', column:'addon_tow'},
  {class:'x',name:'Addon: Windscreen', column:'addon_wind'},
  {class:'x',name:'Addon: Yes/No', column:'addon_n'},

  {class:'x',name:'Motoring Jobs', column:'cad_jobs'},
  {class:'x',name:'Last Motoring Jobs', column:'cad_jobs_dt'},

  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},
  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},
  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},
  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},
  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},
  // {class:'x',name:'Addon: Yes/No', column:'addon_n'},


  {class:'x',name:'Location SA4', column:'loc_sa4'},
  {class:'x',name:'SA4 Region', column:'sa4_code_2016'},
  {class:'x',name:'Location SA4', column:'LOC_SA4'},
  {class:'x',name:'Road Club', column:'road_club'},
  {class:'x',name:'Vehicle Ageband', column:'VEH_AGE_BUCKET',order:['0-3','4-7','8-11','12+','OTHERS']},
  {class:'x',name:'Current Vehicle Ageband', column:'veh_ageband_now',order:['7-9','10-12','13-16','17+','UNKNOWN']},
  {class:'x',name:'Vehicle Body', column:'veh_body'},
  {class:'x',name:'Vehicle Body', column:'vehicle_body'},
  {class:'x',name:'Vehicle Body', column:'VEH_BODY'},
  {class:'x',name:"QUAD",column:"quad",order:['CSC','SE','NW','NE','SW','CAN','NEW','CEN','WOL']},
  {class:'x',name:"Weekday",column:"received_dow",order:['MON','TUE','WED','THU','FRI','SAT','SUN']},
  {class:'x',name:"Weekday",column:"RECEIVED_DOW",order:['MON','TUE','WED','THU','FRI','SAT','SUN']},
  {class:'x',name:"Brand Groups",column:"veh_brand"},
  {class:'x',name:"Brand Groups",column:"VEH_BRAND"},
  // {class:'x',name:"Years Since Last Battery",column:"last_battery",order:['2-3','3-4','4-5','5-6']},
  {class:'x',name:"Years Since Last Battery",column:"last_battery"},
  {class:'x',name:"Days since Breakdown",column:"days_since_band"},
  {class:'x',name:"Recent Breakdown",column:"recent_breakdown"},
  {class:"x", name:"Product Summ",column:"prod_agg1"},
  {class:"x", name:"Repeat Sale Type",column:"battsold_sale_type"},
  {class:"x", name:"Repeat Year",column:"batcyc_band",order:['1-3','3-4','4-5','5-6','6+','Unknown']},
  {class:"x", name:"Business Type",column:"BUSINESS_TYPE"},
  {class:"x", name:"CALLOUT Loc",column:"LOC_REGION"},
  {class:"x", name:"Rego State",column:"VEH_REGO_STATE"},
  {class:"x", name:"Completion Summ",column:"cc_agg1"},
  {class:"x", name:"Breakdown Summ",column:"bc_agg1"},
  {class:"x", name:"Product Summ",column:"prod_agg1"},
  {class:"x", name:"FY",column:"year_fy"},
  {class:"x", name:"Callout Source",column:"RECEIVED_CD"},
  {class:"x", name:"NAPS OEM",column:"prod_naps"},
  {class:"x", name:"Bathrooms",column:"baths"},
  {class:"x", name:"Bedrooms",column:"beds"},
  {class:"x", name:"Property Type",column:"propertyType"},
  {class:"x", name:"Garage",column:"parking"},
  {class:"x", name:"Postcode",column:"postcode"},
  {class:"x", name:"CY",column:"year_cy"},
  {class:"x", name:"Month",column:"month"},
  {class:"x", name:"SA2 region",column:"SA2_NAME"},
  {class:"x", name:"SA3 region",column:"SA3_NAME"},
  {class:"x", name:"SA4 region",column:"SA4_NAME"},
  {class:"x", name:"GCC region",column:"GCCSA_NAME"},
  {class:"x", name:"State Region",column:"STATE_NAME"},
  {class:"x", name:"SA4 region",column:"SA4_NAME_2016"},
  {class:"x", name:"Region",column:"GCCSA_CODE_2016"},
  {class:"x", name:"State",column:"STATE_NAME_2016"},
  {class:"x", name:"Region Cat",column:"region_cat"},
  {class:"x", name:"Region Subcat",column:"region_subcat",order:['Syd North','Syd West','Syd Inner','Syd South','Rural','Reg - ACT','Reg North','Reg South','Reg Newcastle']},
  {class:"x", name:"Member Ageband",column:"member_ageband"},
  {class:"x", name:"Member Colour",column:"member_colour"},
  {class:"x", name:"Member Culture",column:"surname_culture_agg2"},
  {class:"x", name:"Member Culture",column:"surname_culture"},
  // {class:"x", name:"Last Breakdown",column:"recent_mths_band"},
  {class:"x", name:"Months Since Breakdown",column:"recent_mths_band",order:['0-3','4-6','6-12','13-18','no breakdown']},
  {class:"x", name:"Current NRMA Member",column:"active_gms"},
  {class:"x", name:"Current NRMA Member",column:"gms_active"},
  {class:"x", name:"Repeat Prediction Decile",column:"pred_decile_gms"},
  {class:"x", name:"Repeat Prediction Band",column:"pred_hml_gms"},
  {class:"x", name:"NRMA $ Band",column:"price_band",order:['1','2','3','4','5','6','7','8','9','10']},
  {class:"x", name:"NRMA $ Diff Band",column:"price_diff_band",order:['1','2','3','4','5','6','7','8','9','10']},
  {class:"x", name:"Match Customer",column:"match_customerid"},
  {class:"x", name:"Match Car Make",column:"match_veh_make"},
  {class:"x", name:"Match Car Model",column:"match_veh_model"},
  {class:"x", name:"Match Car Year",column:"match_veh_year"},
  {class:"x", name:"Repeat Outcome",column:"repeat_cd"},
  {class:"x", name:"Road Club",column:"ROAD_CLUB"},
  {class:"x", name:"Vehicle Body",column:"VEH_BODY"},
  {class:"x", name:"Vehicle Brand",column:"VEH_BRAND"},
  {class:"x", name:"Vehicle GVM",column:"vehicle_gvm"},
  {class:"x", name:"Vehicle Body",column:"vehicle_body_agg1"},
  // renewals
  {class:"x", name:"Vehicle Age",column:"vehicle_ageband"},
  {class:"x", name:"Product",column:"prod_grp_agg1"},
  {class:"x", name:"Metro Area",column:"sa4_metro_cat"},
  // 
  {class:"x", name:"OMC Sent #",column:"omc_sent"},
  {class:"x", name:"OMC Open #",column:"omc_open"},
  {class:"x", name:"Last OMC Sent",column:"omc_dt_sent"},
  {class:"x", name:"Last OMC Open",column:"omc_dt_open"},
  // 
  {class:"x", name:"AMS Transport",column:"ams_time_Transport"},
  {class:"x", name:"AMS Holiday",column:"ams_time_Holidays"},
  {class:"x", name:"AMS Entertainment",column:"ams_time_Entertainment"},
  {class:"x", name:"AMS Insurance",column:"ams_time_Insurance"},
  {class:"x", name:"AMS Lifestyle",column:"ams_time_Lifestyle"},
  {class:"x", name:"AMS Battery",column:"ams_time_Battery"},
  {class:"x", name:"AMS Fuel",column:"ams_time_Fuel"},
  {class:"x", name:"AMS Car",column:"ams_time_Car"},
  // 
  {class:"x", name:"Loyalty Colour",column:"member_loyalty_colour"},
  {class:"x", name:"Last Payment Ontime",column:"sale_pot"},
  {class:"x", name:"Payment Type",column:"order_pay_type"},
  {class:"x", name:"NRMA Tenure",column:"member_tenure_agg2"},
  {class:"x", name:"Member Gender",column:"member_gender"},
  {class:"x", name:"RDA Culture",column:"rda_culture"},
  {class:"x", name:"Region",column:"sa4_region"},
  {class:"x", name:"Paid / Free",column:"order_payment_cd"},
  {class:"x", name:"MPP",column:"order_payment_term"},
  {class:"x", name:"Lifecycle",column:"rda_lifecycle"},
  {class:"x", name:"Sales Type CSSV",column:"cssv_cd"},
  {class:"x", name:"App Engagement",column:"app_dt_max"},
  {class:"x", name:"Web Engagement",column:"web_dt_max"},
  {class:"x", name:"Web Sessions",column:"web_sessions"},
  {class:"x", name:"App Sessions",column:"app_sessions"},
  {class:"x", name:"Acquisition Type",column:"acq_cd"},
  {class:"x", name:"Promotion Type",column:"sub_promotion"},
  {class:"x", name:"Product Type",column:"prod_sub_type"},
  // dt 
  {class:'dt',name:"Campaign Month",column:"prospect_yyyymm"},
  {class:'dt',name:"Campaign Month",column:"PROSPECT_YYYYMM"},
  {class:"dt", name:"Month",column:"RECEIVED_YYYYMM"},
  {class:"dt", name:"Month",column:"YYYYMM"},
  {class:"dt", name:"Sale Month",column:"sale_yyyymm"},
  {class:"dt", name:"Renewal Month",column:"renewal_yyyymm"},
  {class:"dt", name:"",column:""},
  {class:"dt", name:"",column:""},
  {class:"dt", name:"",column:""},
  {class:"dt", name:"",column:""},

]
